### ISSUE TITLE
Address scan function is not working

### ISSUE THREAD

**Issue by b0rt0l0me0** [Bitcoin-com/Wallet#516]
When I try to activate scan function wallet app turns black and I have to restart app to get back to normal (wallet version v5.6-rc3, android 7.1) or app turns black and crash (wallet version v5.6-rc3, android 5.0).

When I download bitcoin.com-wallet-5.0-rc2-android-derived.apk from https://bitcoin.com and try to install apk, installer complains about corrupt package. 
Google play says I have latest aplication version installed.

How I can get rid of this issue?

**Comment by Bitkilo** [comment]
Thanks for the report. Unfortunately there is no way to get rid of the issue, it's a bug in the app. 
Our developers are working on the problem, and will have this fixed in the next update.

**Comment by balibebas** [comment]
> Our developers are working on the problem, and will have this fixed in the next update.

For the new wallet today with the updated branding and all. Wallet scanning still doesn't work on Huawei. Ditching your wallet for Samourai and Exodus. Please let Rodger know because I know how adament he is about usefulness, of which this app is not.

**Comment by Bitkilo** [comment]
Thank you for the feedback, i will notify the dev team.
Is this happening when you try to scan any QR code, or only a particular QR code?
What model Huawei do you have, and what Android OS is it running?

**Comment by balibebas** [comment]
All QR scanning has been busted for months and results in a black screen of death on Huawei P20 Pro and now P30 Pro anytime a user attempts to scan any QR code just as OP suggests. I imagine the Honor would have the same result and I doubt the issue is isolated to just Huawei phones.

Huawei has HOTA updates and runs the latest version of Android with all security patches always. My particular version is EMUI 9.1 running Android 9.

These issues do not occur with the QR scanning functions in Exodus nor with Samourai. But they make this wallet completely unusable for users and there are many wallets to choose from these days so there's not issue switching. It's a shame I waited as long as I did for this fix based on the earlier comments suggesting this would be fixed in the next version. That's a bad experience.
